//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THCM4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTDH = new HashSet<CTDH>();
            this.CTPN = new HashSet<CTPN>();
        }
        
        public int MaSP { get; set; }
        [DisplayName("Tên Sản Phẩm")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string TenSP { get; set; }
        [DisplayName("Đơn Giá")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayFormat(DataFormatString = "{0:0}", ApplyFormatInEditMode = true)]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Nhập Sai Dữ Liệu")]
        public Nullable<decimal> DonGia { get; set; }
        [DisplayName("Ngày Cập Nhật")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        [DisplayName("Cấu Hình")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string CauHinh { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string Mota { get; set; }
        [DisplayName("Loại ")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public Nullable<int> Loai { get; set; }
        [DisplayName("Hình Ảnh")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string HinhAnh { get; set; }
        [DisplayName("Số Lượng Tồn")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public Nullable<int> SoLuongTon { get; set; }
        [DisplayName("Lượt Xem")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDH> CTDH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPN> CTPN { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        public virtual NCC NCC { get; set; }
        public virtual NSX NSX { get; set; }
    }
}
